var annotated_dup =
[
    [ "CacheInfo", "structCacheInfo.html", "structCacheInfo" ],
    [ "CGroupConfigInfo", "structCGroupConfigInfo.html", "structCGroupConfigInfo" ],
    [ "ClientDataManager", "classClientDataManager.html", "classClientDataManager" ],
    [ "ClientGarbageCollector", "classClientGarbageCollector.html", "classClientGarbageCollector" ],
    [ "ClusterInfo", "structClusterInfo.html", "structClusterInfo" ],
    [ "CocoTable", "classCocoTable.html", "classCocoTable" ],
    [ "ComponentRegistry", "classComponentRegistry.html", null ],
    [ "ExtFeaturesRegistry", "classExtFeaturesRegistry.html", "classExtFeaturesRegistry" ],
    [ "Message", "classMessage.html", "classMessage" ],
    [ "MpamGroupConfigInfo", "structMpamGroupConfigInfo.html", "structMpamGroupConfigInfo" ],
    [ "PropertiesRegistry", "classPropertiesRegistry.html", "classPropertiesRegistry" ],
    [ "PulseMonitor", "classPulseMonitor.html", "classPulseMonitor" ],
    [ "RateLimiter", "classRateLimiter.html", "classRateLimiter" ],
    [ "Request", "classRequest.html", "classRequest" ],
    [ "RequestManager", "classRequestManager.html", "classRequestManager" ],
    [ "RequestQueue", "classRequestQueue.html", null ],
    [ "RequestReceiver", "classRequestReceiver.html", null ],
    [ "ResConfInfo", "structResConfInfo.html", "structResConfInfo" ],
    [ "Resource", "classResource.html", "classResource" ],
    [ "ResourceApplyType", "structResourceApplyType.html", null ],
    [ "ResourceRegistry", "classResourceRegistry.html", "classResourceRegistry" ],
    [ "RestuneParser", "classRestuneParser.html", null ],
    [ "Signal", "classSignal.html", "classSignal" ],
    [ "SignalInfo", "structSignalInfo.html", "structSignalInfo" ],
    [ "SignalRegistry", "classSignalRegistry.html", "classSignalRegistry" ],
    [ "SysResource", "structSysResource.html", "structSysResource" ],
    [ "TargetRegistry", "classTargetRegistry.html", "classTargetRegistry" ]
];