var searchData=
[
  ['sample_20cgroup_20config_0',['Sample Cgroup config',['../usage.html#autotoc_md102',1,'']]],
  ['sample_20device_20config_20file_1',['Sample Device Config file',['../usage.html#autotoc_md105',1,'']]],
  ['sample_20properties_20config_20file_2',['Sample Properties config file.',['../usage.html#autotoc_md108',1,'']]],
  ['sample_20resource_20config_20file_20with_20two_20resources_3',['Sample Resource config file with two resources.',['../usage.html#autotoc_md96',1,'']]],
  ['scenario_20tuning_4',['1.3.2 Use-case/Workload/Scenario Tuning',['../index.html#autotoc_md7',1,'']]],
  ['send_20a_20getprop_20request_5',['send a getprop request',['../client_cli.html#autotoc_md83',1,'4. Send a getProp Request'],['../index.html#autotoc_md44',1,'5.4. Send a getProp Request']]],
  ['send_20a_20retune_20request_6',['send a retune request',['../client_cli.html#autotoc_md82',1,'3. Send a Retune Request'],['../index.html#autotoc_md43',1,'5.3. Send a Retune Request']]],
  ['send_20a_20tune_20request_7',['send a tune request',['../client_cli.html#autotoc_md80',1,'1. Send a Tune Request'],['../index.html#autotoc_md41',1,'5.1. Send a Tune Request']]],
  ['send_20a_20tunesignal_20request_8',['send a tunesignal request',['../client_cli.html#autotoc_md84',1,'5. Send a tuneSignal Request'],['../index.html#autotoc_md45',1,'5.5. Send a tuneSignal Request']]],
  ['send_20an_20untune_20request_9',['send an untune request',['../client_cli.html#autotoc_md81',1,'2. Send an Untune Request'],['../index.html#autotoc_md42',1,'5.2. Send an Untune Request']]],
  ['should_20the_20extfeaturesconfig_20yaml_20be_20placed_10',['3. Where should the ExtFeaturesConfig.yaml be placed?',['../ext_features.html#autotoc_md93',1,'']]],
  ['shouldrequestbeadded_11',['shouldRequestBeAdded',['../classRequestManager.html#af467481df904900af4035c7c4e993603',1,'RequestManager']]],
  ['sigcode_12',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md109',1,'']]],
  ['signal_13',['Signal',['../classSignal.html',1,'']]],
  ['signal_20code_20construction_14',['4.2.4.1. Signal Code Construction',['../index.html#autotoc_md27',1,'']]],
  ['signal_20configs_15',['signal configs',['../index.html#autotoc_md37',1,'4.3.4. Signal Configs'],['../index.html#autotoc_md55',1,'6.2.4. Signal Configs']]],
  ['signal_20opcode_20sigcode_16',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md109',1,'']]],
  ['signalinfo_17',['SignalInfo',['../structSignalInfo.html',1,'']]],
  ['signalinternal_2eh_18',['SignalInternal.h',['../SignalInternal_8h.html',1,'']]],
  ['signalregistry_19',['SignalRegistry',['../classSignalRegistry.html',1,'']]],
  ['signals_20',['signals',['../index.html#autotoc_md11',1,'3. Configurable Resources and Signals'],['../index.html#autotoc_md13',1,'3.2. Signals']]],
  ['signals_20and_20features_21',['1. Making Use of Relay Signals and Features',['../ext_features.html#autotoc_md89',1,'']]],
  ['startclientgarbagecollectordaemon_22',['startClientGarbageCollectorDaemon',['../classClientGarbageCollector.html#a6012f1e50f06f70d1640944ce6314fd8',1,'ClientGarbageCollector']]],
  ['started_23',['2. Getting Started',['../index.html#autotoc_md10',1,'']]],
  ['startpulsemonitordaemon_24',['startPulseMonitorDaemon',['../classPulseMonitor.html#a8932d2321e409e049b8f55cfe3b9c120',1,'PulseMonitor']]],
  ['structure_25',['7.1. Project Structure',['../index.html#autotoc_md59',1,'']]],
  ['submitpropgetrequest_26',['submitPropGetRequest',['../RestuneInternal_8h.html#a7a59c236188fb4446fee3401d299d7cf',1,'RestuneInternal.h']]],
  ['submitresprovisionreqmsg_27',['submitResProvisionReqMsg',['../RestuneInternal_8h.html#a0b4e3e16698adef003b71aa9546718e5',1,'RestuneInternal.h']]],
  ['submitsignalrequest_28',['submitSignalRequest',['../SignalInternal_8h.html#a8afb0e0e0e8c22624fac55d0a7ea0d83',1,'SignalInternal.h']]],
  ['subsequent_20cleanup_29',['7.6. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md68',1,'']]],
  ['sysresource_30',['sysresource',['../index.html#autotoc_md18',1,'4.2.1.1. SysResource'],['../structSysResource.html',1,'SysResource']]],
  ['system_20abuse_31',['7.7. Rate Limiter: Preventing System Abuse',['../index.html#autotoc_md69',1,'']]],
  ['system_20resource_20tuning_20framework_32',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]],
  ['system_20resources_33',['1.3.1 Provisioning System Resources',['../index.html#autotoc_md6',1,'']]]
];
