var searchData=
[
  ['table_20cocotable_0',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['table_20of_20contents_1',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['target_20configs_2',['6.2.5. Target Configs',['../index.html#autotoc_md56',1,'']]],
  ['target_20information_3',['6.1.2. Fetching Target Information',['../index.html#autotoc_md49',1,'']]],
  ['targetregistry_4',['TargetRegistry',['../classTargetRegistry.html',1,'']]],
  ['targetregistry_2eh_5',['TargetRegistry.h',['../TargetRegistry_8h.html',1,'']]],
  ['teardown_20callbacks_6',['2. Applier and Teardown Callbacks',['../extensions_usage.html#autotoc_md86',1,'']]],
  ['teardown_20capabilities_7',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md91',1,'']]],
  ['teardownfeatures_8',['teardownFeatures',['../classExtFeaturesRegistry.html#aa563b40b2c05933b18e64f4597ae251a',1,'ExtFeaturesRegistry']]],
  ['the_20extfeaturesconfig_20yaml_20be_20placed_9',['3. Where should the ExtFeaturesConfig.yaml be placed?',['../ext_features.html#autotoc_md93',1,'']]],
  ['the_20resource_20tune_20and_20untune_20functionalities_10',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md99',1,'']]],
  ['to_20add_20a_20custom_20resource_11',['1. How to add a custom resource',['../usage.html#autotoc_md95',1,'']]],
  ['to_20add_20a_20new_20property_12',['5. How to add a new Property',['../usage.html#autotoc_md107',1,'']]],
  ['to_20add_20init_20configs_13',['3. How to add init configs',['../usage.html#autotoc_md101',1,'']]],
  ['to_20create_20a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_14',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md109',1,'']]],
  ['to_20enforce_20cpu_20architecture_20details_15',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md104',1,'']]],
  ['to_20override_20the_20resource_20tune_20and_20untune_20functionalities_16',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md99',1,'']]],
  ['to_20physical_20mapping_17',['7.9. Dynamic Mapper: Logical to Physical Mapping',['../index.html#autotoc_md71',1,'']]],
  ['tune_20and_20untune_20functionalities_18',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md99',1,'']]],
  ['tune_20request_19',['tune request',['../client_cli.html#autotoc_md80',1,'1. Send a Tune Request'],['../index.html#autotoc_md41',1,'5.1. Send a Tune Request']]],
  ['tune_20requests_20formulation_20guide_20',['&quot;Tune&quot; Requests Formulation Guide',['../requests_formulation.html',1,'']]],
  ['tuner_21',['7.2.2. Resource Tuner',['../index.html#autotoc_md62',1,'']]],
  ['tuneresources_22',['tuneresources',['../index.html#autotoc_md17',1,'4.2.1. tuneResources'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga1eac546e5691c0c3d5d7036a68ba6a2b',1,'tuneResources():&#160;UrmAPIs.h']]],
  ['tunesignal_23',['tunesignal',['../index.html#autotoc_md26',1,'4.2.4. tuneSignal'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga3c652f0874217ba2df98289c8c556311',1,'tuneSignal():&#160;UrmAPIs.h']]],
  ['tunesignal_20request_24',['tunesignal request',['../client_cli.html#autotoc_md84',1,'5. Send a tuneSignal Request'],['../index.html#autotoc_md45',1,'5.5. Send a tuneSignal Request']]],
  ['tuning_25',['tuning',['../index.html#autotoc_md7',1,'1.3.2 Use-case/Workload/Scenario Tuning'],['../index.html#autotoc_md8',1,'1.3.3 Per-App tuning']]],
  ['tuning_20framework_26',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]],
  ['two_20resources_27',['Sample Resource config file with two resources.',['../usage.html#autotoc_md96',1,'']]]
];
