var searchData=
[
  ['a_20custom_20resource_0',['1. How to add a custom resource',['../usage.html#autotoc_md95',1,'']]],
  ['a_20getprop_20request_1',['a getprop request',['../client_cli.html#autotoc_md83',1,'4. Send a getProp Request'],['../index.html#autotoc_md44',1,'5.4. Send a getProp Request']]],
  ['a_20new_20property_2',['5. How to add a new Property',['../usage.html#autotoc_md107',1,'']]],
  ['a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_3',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md109',1,'']]],
  ['a_20retune_20request_4',['a retune request',['../client_cli.html#autotoc_md82',1,'3. Send a Retune Request'],['../index.html#autotoc_md43',1,'5.3. Send a Retune Request']]],
  ['a_20system_20resource_20tuning_20framework_5',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]],
  ['a_20tune_20request_6',['a tune request',['../client_cli.html#autotoc_md80',1,'1. Send a Tune Request'],['../index.html#autotoc_md41',1,'5.1. Send a Tune Request']]],
  ['a_20tunesignal_20request_7',['a tunesignal request',['../client_cli.html#autotoc_md84',1,'5. Send a tuneSignal Request'],['../index.html#autotoc_md45',1,'5.5. Send a tuneSignal Request']]],
  ['abstraction_20layer_8',['4.1. Platform Abstraction Layer',['../index.html#autotoc_md15',1,'']]],
  ['abuse_9',['7.7. Rate Limiter: Preventing System Abuse',['../index.html#autotoc_md69',1,'']]],
  ['add_20a_20custom_20resource_10',['1. How to add a custom resource',['../usage.html#autotoc_md95',1,'']]],
  ['add_20a_20new_20property_11',['5. How to add a new Property',['../usage.html#autotoc_md107',1,'']]],
  ['add_20init_20configs_12',['3. How to add init configs',['../usage.html#autotoc_md101',1,'']]],
  ['addrequest_13',['addRequest',['../classRequestManager.html#aa819a5b2d3c9be0a29b9075b276b9518',1,'RequestManager']]],
  ['allocate_20capacity_20for_20efficiency_14',['7.13. Pre-Allocate Capacity for efficiency',['../index.html#autotoc_md75',1,'']]],
  ['an_20untune_20request_15',['an untune request',['../client_cli.html#autotoc_md81',1,'2. Send an Untune Request'],['../index.html#autotoc_md42',1,'5.2. Send an Untune Request']]],
  ['and_20features_16',['1. Making Use of Relay Signals and Features',['../ext_features.html#autotoc_md89',1,'']]],
  ['and_20signal_20opcode_20sigcode_17',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md109',1,'']]],
  ['and_20signals_18',['3. Configurable Resources and Signals',['../index.html#autotoc_md11',1,'']]],
  ['and_20subsequent_20cleanup_19',['7.6. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md68',1,'']]],
  ['and_20teardown_20callbacks_20',['2. Applier and Teardown Callbacks',['../extensions_usage.html#autotoc_md86',1,'']]],
  ['and_20teardown_20capabilities_21',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md91',1,'']]],
  ['and_20untune_20functionalities_22',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md99',1,'']]],
  ['apis_23',['apis',['../index.html#autotoc_md16',1,'4.2. URM APIs'],['../group__RESOURCE__TUNER__CLIENT__APIS.html',1,'Client APIs']]],
  ['app_20configs_24',['4.3.5. Per App Configs',['../index.html#autotoc_md38',1,'']]],
  ['app_20tuning_25',['1.3.3 Per-App tuning',['../index.html#autotoc_md8',1,'']]],
  ['applier_20and_20teardown_20callbacks_26',['2. Applier and Teardown Callbacks',['../extensions_usage.html#autotoc_md86',1,'']]],
  ['architecture_20details_27',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md104',1,'']]],
  ['aware_20operational_20modes_28',['7.10. Display-Aware Operational Modes',['../index.html#autotoc_md72',1,'']]]
];
