var searchData=
[
  ['rate_20limiter_0',['Rate Limiter',['../group__RATE__LIMITER.html',1,'']]],
  ['rate_20limiter_3a_20preventing_20system_20abuse_1',['7.7. Rate Limiter: Preventing System Abuse',['../index.html#autotoc_md69',1,'']]],
  ['ratelimiter_2',['RateLimiter',['../classRateLimiter.html',1,'']]],
  ['ratelimiter_2eh_3',['RateLimiter.h',['../RateLimiter_8h.html',1,'']]],
  ['readtargetinfo_4',['readTargetInfo',['../classTargetRegistry.html#a3f2d96aefc2104ff5761602b20f5a8a4',1,'TargetRegistry']]],
  ['recovery_5',['7.11. Crash Recovery',['../index.html#autotoc_md73',1,'']]],
  ['registering_20custom_20configs_6',['6.1.3. Registering Custom Configs',['../index.html#autotoc_md50',1,'']]],
  ['registering_20resource_20callbacks_7',['6.1.1. Registering Resource Callbacks',['../index.html#autotoc_md48',1,'']]],
  ['registerresource_8',['registerResource',['../classResourceRegistry.html#ab8a34e31c27f3676aa82bc81c08fb6b9',1,'ResourceRegistry']]],
  ['registersignal_9',['registerSignal',['../classSignalRegistry.html#abd369ba19f90f6f2b4864c939e7f67b1',1,'SignalRegistry']]],
  ['relay_20and_20teardown_20capabilities_10',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md91',1,'']]],
  ['relay_20signals_20and_20features_11',['1. Making Use of Relay Signals and Features',['../ext_features.html#autotoc_md89',1,'']]],
  ['relaysignal_12',['relaysignal',['../index.html#autotoc_md30',1,'4.2.6. relaySignal'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga5a4249a35267efc5c291069ca1a028e1',1,'relaySignal():&#160;UrmAPIs.h']]],
  ['relaytofeature_13',['relayToFeature',['../classExtFeaturesRegistry.html#a4e4331eae9f156bcc983eda62f4bfe74',1,'ExtFeaturesRegistry']]],
  ['removerequest_14',['removerequest',['../classCocoTable.html#a74d26e26627f9b1fff71222543b3b97a',1,'CocoTable::removeRequest()'],['../classRequestManager.html#ab9dd675017b66476e2dfa7ce4389023f',1,'RequestManager::removeRequest()']]],
  ['request_15',['request',['../client_cli.html#autotoc_md80',1,'1. Send a Tune Request'],['../client_cli.html#autotoc_md81',1,'2. Send an Untune Request'],['../client_cli.html#autotoc_md82',1,'3. Send a Retune Request'],['../client_cli.html#autotoc_md83',1,'4. Send a getProp Request'],['../client_cli.html#autotoc_md84',1,'5. Send a tuneSignal Request'],['../index.html#autotoc_md41',1,'5.1. Send a Tune Request'],['../index.html#autotoc_md42',1,'5.2. Send an Untune Request'],['../index.html#autotoc_md43',1,'5.3. Send a Retune Request'],['../index.html#autotoc_md44',1,'5.4. Send a getProp Request'],['../index.html#autotoc_md45',1,'5.5. Send a tuneSignal Request'],['../classRequest.html',1,'Request']]],
  ['request_20level_20priorities_16',['7.5. Request-Level Priorities',['../index.html#autotoc_md67',1,'']]],
  ['request_20processing_17',['7.2.4. Request Processing',['../index.html#autotoc_md64',1,'']]],
  ['requestmanager_18',['RequestManager',['../classRequestManager.html',1,'']]],
  ['requestqueue_19',['RequestQueue',['../classRequestQueue.html',1,'']]],
  ['requestreceiver_20',['RequestReceiver',['../classRequestReceiver.html',1,'']]],
  ['requests_20formulation_20guide_21',['&quot;Tune&quot; Requests Formulation Guide',['../requests_formulation.html',1,'']]],
  ['requesttype_22',['RequestType',['../Utils_8h.html#aae642cee2f4be03d228c36c0ccf8faef',1,'Utils.h']]],
  ['rescode_20and_20signal_20opcode_20sigcode_23',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md109',1,'']]],
  ['rescode_20construction_24',['4.2.1.2. Resource ResCode Construction',['../index.html#autotoc_md19',1,'']]],
  ['resconfinfo_25',['ResConfInfo',['../structResConfInfo.html',1,'']]],
  ['resinfo_20construction_26',['4.2.1.3. Resource ResInfo Construction',['../index.html#autotoc_md20',1,'']]],
  ['resource_27',['resource',['../usage.html#autotoc_md95',1,'1. How to add a custom resource'],['../classResource.html',1,'Resource']]],
  ['resource_20callbacks_28',['6.1.1. Registering Resource Callbacks',['../index.html#autotoc_md48',1,'']]],
  ['resource_20config_20file_20with_20two_20resources_29',['Sample Resource config file with two resources.',['../usage.html#autotoc_md96',1,'']]],
  ['resource_20configs_30',['resource configs',['../index.html#autotoc_md35',1,'4.3.2. Resource Configs'],['../index.html#autotoc_md53',1,'6.2.2. Resource Configs']]],
  ['resource_20indexing_31',['Notes on Resource Indexing',['../usage.html#autotoc_md97',1,'']]],
  ['resource_20level_20policies_32',['7.4. Resource-Level Policies',['../index.html#autotoc_md66',1,'']]],
  ['resource_20manager_20key_20points_33',['7.2. Userspace Resource Manager Key Points',['../index.html#autotoc_md60',1,'']]],
  ['resource_20manager_3a_20a_20system_20resource_20tuning_20framework_34',['Userspace Resource Manager: A System Resource Tuning Framework',['../index.html',1,'']]],
  ['resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_35',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md109',1,'']]],
  ['resource_20rescode_20construction_36',['4.2.1.2. Resource ResCode Construction',['../index.html#autotoc_md19',1,'']]],
  ['resource_20resinfo_20construction_37',['4.2.1.3. Resource ResInfo Construction',['../index.html#autotoc_md20',1,'']]],
  ['resource_20tune_20and_20untune_20functionalities_38',['2. How to override the Resource tune and untune functionalities.',['../usage.html#autotoc_md99',1,'']]],
  ['resource_20tuner_39',['7.2.2. Resource Tuner',['../index.html#autotoc_md62',1,'']]],
  ['resourceapplytype_40',['ResourceApplyType',['../structResourceApplyType.html',1,'']]],
  ['resourceregistry_41',['ResourceRegistry',['../classResourceRegistry.html',1,'']]],
  ['resources_42',['resources',['../index.html#autotoc_md6',1,'1.3.1 Provisioning System Resources'],['../index.html#autotoc_md12',1,'3.1. Resources'],['../usage.html#autotoc_md96',1,'Sample Resource config file with two resources.']]],
  ['resources_20and_20signals_43',['3. Configurable Resources and Signals',['../index.html#autotoc_md11',1,'']]],
  ['restuneinternal_2eh_44',['RestuneInternal.h',['../RestuneInternal_8h.html',1,'']]],
  ['restuneparser_45',['RestuneParser',['../classRestuneParser.html',1,'']]],
  ['retune_20request_46',['retune request',['../client_cli.html#autotoc_md82',1,'3. Send a Retune Request'],['../index.html#autotoc_md43',1,'5.3. Send a Retune Request']]],
  ['retuneresources_47',['retuneresources',['../index.html#autotoc_md22',1,'4.2.2. retuneResources'],['../group__RESOURCE__TUNER__CLIENT__APIS.html#ga3e60de0521a903c940e47f2c0a1ced5a',1,'retuneResources():&#160;UrmAPIs.h']]]
];
