var searchData=
[
  ['cacheinfo_0',['CacheInfo',['../structCacheInfo.html',1,'']]],
  ['callbacks_1',['callbacks',['../extensions_usage.html#autotoc_md86',1,'2. Applier and Teardown Callbacks'],['../index.html#autotoc_md48',1,'6.1.1. Registering Resource Callbacks']]],
  ['capabilities_2',['2. Defining feature init, relay and teardown capabilities',['../ext_features.html#autotoc_md91',1,'']]],
  ['capacity_20for_20efficiency_3',['7.13. Pre-Allocate Capacity for efficiency',['../index.html#autotoc_md75',1,'']]],
  ['case_20workload_20scenario_20tuning_4',['1.3.2 Use-case/Workload/Scenario Tuning',['../index.html#autotoc_md7',1,'']]],
  ['cgroup_20config_5',['Sample Cgroup config',['../usage.html#autotoc_md102',1,'']]],
  ['cgroupconfiginfo_6',['CGroupConfigInfo',['../structCGroupConfigInfo.html',1,'']]],
  ['checking_7',['7.8. Duplicate Checking',['../index.html#autotoc_md70',1,'']]],
  ['classifier_8',['7.2.1. Contextual Classifier',['../index.html#autotoc_md61',1,'']]],
  ['cleanup_9',['7.6. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md68',1,'']]],
  ['cli_10',['cli',['../index.html#autotoc_md40',1,'5. Client CLI'],['../client_cli.html#autotoc_md78',1,'Client CLI'],['../client_cli.html',1,'Interacting via Client CLI']]],
  ['client_20apis_11',['Client APIs',['../group__RESOURCE__TUNER__CLIENT__APIS.html',1,'']]],
  ['client_20cli_12',['client cli',['../index.html#autotoc_md40',1,'5. Client CLI'],['../client_cli.html#autotoc_md78',1,'Client CLI'],['../client_cli.html',1,'Interacting via Client CLI']]],
  ['client_20garbage_20collector_13',['Client Garbage Collector',['../group__CLIENT__GARBAGE__COLLECTOR.html',1,'']]],
  ['client_20level_20permissions_14',['7.3. Client-Level Permissions',['../index.html#autotoc_md65',1,'']]],
  ['clientdatamanager_15',['ClientDataManager',['../classClientDataManager.html',1,'']]],
  ['clientexists_16',['clientExists',['../classClientDataManager.html#abb3fdb175d0d1b3fca56f18d62a4c3a4',1,'ClientDataManager']]],
  ['clientgarbagecollector_17',['ClientGarbageCollector',['../classClientGarbageCollector.html',1,'']]],
  ['clientgarbagecollector_2eh_18',['ClientGarbageCollector.h',['../ClientGarbageCollector_8h.html',1,'']]],
  ['clients_20and_20subsequent_20cleanup_19',['7.6. Pulse Monitor: Detection of Dead Clients and Subsequent Cleanup',['../index.html#autotoc_md68',1,'']]],
  ['clusterinfo_20',['ClusterInfo',['../structClusterInfo.html',1,'']]],
  ['cocotable_21',['cocotable',['../classCocoTable.html',1,'CocoTable'],['../group__COCO__TABLE.html',1,'Concurrency Coordinator Table (CocoTable)']]],
  ['cocotable_2eh_22',['CocoTable.h',['../CocoTable_8h.html',1,'']]],
  ['code_20construction_23',['4.2.4.1. Signal Code Construction',['../index.html#autotoc_md27',1,'']]],
  ['collector_24',['Client Garbage Collector',['../group__CLIENT__GARBAGE__COLLECTOR.html',1,'']]],
  ['componentregistry_25',['ComponentRegistry',['../classComponentRegistry.html',1,'']]],
  ['concurrency_20coordinator_20table_20cocotable_26',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['config_27',['config',['../index.html#autotoc_md36',1,'4.3.3. Properties Config'],['../index.html#autotoc_md54',1,'6.2.3. Properties Config'],['../usage.html#autotoc_md102',1,'Sample Cgroup config']]],
  ['config_20file_28',['config file',['../usage.html#autotoc_md105',1,'Sample Device Config file'],['../usage.html#autotoc_md108',1,'Sample Properties config file.']]],
  ['config_20file_20with_20two_20resources_29',['Sample Resource config file with two resources.',['../usage.html#autotoc_md96',1,'']]],
  ['config_20parsing_30',['4.4. Urm Config Parsing',['../index.html#autotoc_md39',1,'']]],
  ['configs_31',['configs',['../extensions_usage.html#autotoc_md87',1,'3. Custom Configs'],['../usage.html#autotoc_md101',1,'3. How to add init configs'],['../index.html#autotoc_md33',1,'4.3. Configs'],['../index.html#autotoc_md34',1,'4.3.1. Initialization Configs'],['../index.html#autotoc_md35',1,'4.3.2. Resource Configs'],['../index.html#autotoc_md37',1,'4.3.4. Signal Configs'],['../index.html#autotoc_md38',1,'4.3.5. Per App Configs'],['../index.html#autotoc_md50',1,'6.1.3. Registering Custom Configs'],['../index.html#autotoc_md51',1,'6.2. Custom Configs'],['../index.html#autotoc_md52',1,'6.2.1. Initialization Configs'],['../index.html#autotoc_md53',1,'6.2.2. Resource Configs'],['../index.html#autotoc_md55',1,'6.2.4. Signal Configs'],['../index.html#autotoc_md56',1,'6.2.5. Target Configs']]],
  ['configurable_20resources_20and_20signals_32',['3. Configurable Resources and Signals',['../index.html#autotoc_md11',1,'']]],
  ['construction_33',['construction',['../index.html#autotoc_md19',1,'4.2.1.2. Resource ResCode Construction'],['../index.html#autotoc_md20',1,'4.2.1.3. Resource ResInfo Construction'],['../index.html#autotoc_md27',1,'4.2.4.1. Signal Code Construction']]],
  ['contact_34',['8. Contact',['../index.html#autotoc_md76',1,'']]],
  ['contents_35',['Table of Contents',['../index.html#autotoc_md1',1,'']]],
  ['contextual_20classifier_36',['7.2.1. Contextual Classifier',['../index.html#autotoc_md61',1,'']]],
  ['coordinator_20table_20cocotable_37',['Concurrency Coordinator Table (CocoTable)',['../group__COCO__TABLE.html',1,'']]],
  ['cpu_20architecture_20details_38',['4. How to enforce CPU architecture details',['../usage.html#autotoc_md104',1,'']]],
  ['crash_20recovery_39',['7.11. Crash Recovery',['../index.html#autotoc_md73',1,'']]],
  ['create_20a_20resource_20opcode_20rescode_20and_20signal_20opcode_20sigcode_40',['6. How to create a Resource Opcode (ResCode) and Signal Opcode (SigCode)',['../usage.html#autotoc_md109',1,'']]],
  ['createnewclient_41',['createNewClient',['../classClientDataManager.html#acee4333a94f31bd77ec9e31d7bc6353c',1,'ClientDataManager']]],
  ['createproperty_42',['createProperty',['../classPropertiesRegistry.html#ae0a22440795ed868651da51f8af43f85',1,'PropertiesRegistry']]],
  ['custom_20configs_43',['custom configs',['../extensions_usage.html#autotoc_md87',1,'3. Custom Configs'],['../index.html#autotoc_md50',1,'6.1.3. Registering Custom Configs'],['../index.html#autotoc_md51',1,'6.2. Custom Configs']]],
  ['custom_20resource_44',['1. How to add a custom resource',['../usage.html#autotoc_md95',1,'']]],
  ['customizations_20extensions_45',['6. Customizations &amp; Extensions',['../index.html#autotoc_md46',1,'']]]
];
